# Generated by Django 4.2.4 on 2024-12-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('deposits_app', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.TextField()),
            ],
            options={
                'db_table': 'attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributesServicesMm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_id', models.IntegerField()),
                ('serv_id', models.IntegerField()),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attributes_services_mm',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits_app.customuser')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'db_table': 'custom_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='CustomUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposits_app.customuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'db_table': 'custom_user_groups',
            },
        ),
    ]
