# Generated by Django 4.2.4 on 2024-12-22 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits_app', '0003_attributes_attributesservicesmm_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
